### PR TITLE
feat: add all-contributors config file

### LINKED ISSUE #1: Get AllContributors bot set up for this

### PR DESCRIPTION
**Pull request by mtfoley**
To help fix #1 .

### CODE REVIEW

**Comment by clarkio** [comment]
Nice! I think we may need an owner to allow the @allcontributors-bot access to the repo. cc: @FiniteSingularity  @j-dogcoder

**Comment by jaspermayone** [comment]
@FiniteSingularity Is the only one with admin access currently.

**Comment by clarkio** [comment]
Setup doc for reference: https://allcontributors.org/docs/en/bot/installation

**Comment by FiniteSingularity** [comment]
Bot access has now been approved (sorry for the delay.. I was unplugged all weekend).  Please let me know if there is something else I need to do.

**Comment by mtfoley** [comment]
@clarkio I feel like I've got the README and stuff ready for keeping an all-contributors badge at the top linking to the contributors table section.

**Review by clarkio — APPROVED** [review]
Looks good to me. Thanks for getting this set up 👍

**Pull request merged**
